baseURL: https://xiang.dev/
languageCode: en-us
title: Just another developer
theme: ["hugo-notice", "PaperMod"]
paginate: 5

menu:
  main:
    - name: Search
      url: search/
      weight: 9
    - name: Tags
      url: tags/
      weight: 10
    - name: About
      url: /about/
    - name: Projects
      url: /projects/

params:
  env: production
  title: Just another developer
  description: "Personal website of Xiang Chen, software engineer based in Spain"
  keywords: [Blog, Portfolio, Xiang Chen]
  author: Xiang Chen

  homeInfoParams:
    Title: Xiang Chen
    Content: Full time programmer, part time casual

  ShowReadingTime: true
  showToc: true
  TocOpen: false
  hideSummary: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true

  socialIcons:
    - name: github
      url: "https://github.com/stradivari96"
    - name: email
      url: "mailto:chen@xiang.dev"
    - name: linkedin
      url: "https://www.linkedin.com/in/xiang-chen-chen/"
    - name: twitter
      url: "https://twitter.com/xiang_96"
    - name: Rss
      url: "index.xml"

  assets:
    disableHLJS: true

markup:
  highlight:
    lineNos: false
    style: monokai
  goldmark:
    renderer:
      unsafe: true

disqusShortname: stradivari96

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
