baseURL: https://xiang.dev/
languageCode: en-us
title: Just another developer
theme: ["hugo-notice", "PaperMod"]

menu:
  main:
    - identifier: About
      name: About
      url: /about/

params:
  env: production
  title: Just another developer
  description: "Personal website of Xiang Chen, software engineer based in Spain"
  keywords: [Blog, Portfolio, Xiang Chen]
  author: Xiang Chen

  homeInfoParams:
    Title: Xiang Chen
    Content: Full time programmer, part time casual

  ShowReadingTime: true
  showToc: true
  TocOpen: false
  hideSummary: false

  socialIcons:
    - name: github
      url: "https://github.com/stradivari96"
    - name: email
      url: "mailto:chen@xiang.dev"
    - name: linkedin
      url: "https://www.linkedin.com/in/xiang-chen-chen/"
    - name: twitter
      url: "https://twitter.com/xiang_96"
    - name: Rss
      url: "index.xml"

markup:
  goldmark:
    renderer:
      unsafe: true
