name: Main

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: 'curl -X POST -sS "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" -H "Content-Type: application/json" -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" --data "{\"purge_everything\":true}"'
